# --- Library ----------
library(tidyverse)
library(nnet) # multinom, which.is.max

# --- Functions (data) ----------
# generate the full data
fn_dataGenF <- function(beta, # 2*3 vector
                        N = 3000,
                        pe = 0.4, # P(X2), exposure
                        pa = 0.9, # assuming sp=se
                        seed = 2025
){
  # ```params```
  # seed = 2025
  # pe = 0.4 # P(X2)
  # pa = 0.9 # se & sp
  # beta = c(-1.75,1.00,1.00,  # for Y=1
  #           -0.70,1.70,-0.20) # for Y=2
  # ````````````
  set.seed(seed)
  N = 3000
  K = 3 # number of level of Y (0-No,1-Yes,2-Not sure)
  k = K-1 # 2
  M = 2  # number of covariates (without 1) 
  m = M+1 # number of coefficient for covariates
  
  # parameter (k*m)
  betam <- matrix(beta,nrow = k,ncol = m,byrow = TRUE)
  
  # covariates X (N*m)
  x1 <- rbinom(N,1,0.5)
  x2 <- rbinom(N,1,pe)
  X <- cbind(x1,x2)
  Xwith1 <- cbind(1,X)
  
  # probability P (N*K)
  P = cbind(0,Xwith1%*% t(betam)) %>% exp()
  
  # response variable Y (n*K), y (n*1)
  Y = sapply(1:N, function(i){c(rmultinom(1,1,P[i,]))}) %>% t()
  y = apply(Y,1,which.is.max) - 1
  
  # surrogate S (N*1)
  ps = pa * (y==1) + (1-pa) * (y==0) + 0.4 * (y==2)
  s = rbinom(N,1,ps)
  
  Fd = as.data.frame(cbind(y,s,X))
  Fd$y = factor(Fd$y,levels = c('0','1','2'))
  return(Fd)
}

# generate the biased validation set
fn_dataGenV <- function(Fd,n0=300,n1=300,
                        seed = 2025,
                        threshold=5){
  # Fd is generated by`dataGenF`
  # Fd = fn_dataGenF(beta = c(-1.75,1.00,1.00,-0.70,1.70,-0.20))
  # n0=300;n1=300
  # threshold=5
  set.seed(seed)
  
  s = Fd[,'s']
  i0 = which(s==0)
  i1 = which(s==1)
  
  # check 1
  if(length(i0) < n0 | length(i1) < n1){
    n0 = min(length(i0),n0)
    n1 = min(length(i1),n1)
    warning(sprintf('BIASED SAMPLING RESET: n0=%i, n1=%i',n0,n1))
  }
  
  # check 2
  nvy = 0 # num of y = 1 (yes) in validation set
  nrep = 0
  while(nvy <= threshold){
    iv = c(sample(i0,n0,replace = F), sample(i1,n1,replace = F))
    nvy = min(table(Fd[iv,'y']))
    nrep = nrep+1
  }
  if(nrep>1){message(sprintf('BIASED SAMPLING REPEAT %i TIMES',nrep))}
  
  # set validation set
  Fd[-iv,'y'] <- NA
  return(Fd)
}

# generate the random validation set
fn_dataGenU <- function(Fd,n=600,seed = 2025,threshold=5){
  set.seed(seed)
  nuy = 0
  N = nrow(Fd)
  while(nuy <= threshold){
    iu = sample(1:N,n,replace = F)
    nuy = min(table(Fd[iu,'y']))
  }
  # set validation set
  Fd[-iu,'y'] <- NA
  return(Fd)
}



# --- Functions (estimator) ----------

fn_oracle <- function(fdata,xchar,ychar){
  # fdata = tmpv
  # xchar = c('x1','x2')
  # ychar = 'y'
  # schar = 's'
  
  
  ## Models: Full set; true outcomes
  fmly <- reformulate(xchar,response = ychar)
  FTmd <- multinom(fmly,data = fdata,Hess = TRUE,trace=FALSE)
  BF = coef(FTmd)
  BFV = vcov(FTmd) 
  FTres = list("coef" = c(t(BF)),"std"=sqrt(diag(BFV))) # to be returned to compare
  return(FTres)
}


# biased sampling (method 2 & TriCA)
# method 2: Y~X on V
# TriCA: augmented on V
fn_bias <- function(fdata,xchar,ychar,schar){
  # fdata = tmpv
  # xchar = c('x1','x2')
  # ychar = 'y'
  # schar = 's'
  
  fy = fdata[[ychar]]
  # TODO: to be checked (for the `multinom`)
  if(!is.factor(fy)){fdata[[ychar]] = factor(fy)}
  # fy = fdata[[ychar]]
  fs = fdata[[schar]]
  
  vdata = subset(fdata, subset = !is.na(fy))
  # vy = vdata[[ychar]]
  vs = vdata[[schar]]
  
  N = nrow(fdata)
  n = nrow(vdata)
  
  fmly <- reformulate(xchar,response = ychar)
  fmls <- reformulate(xchar,response = schar)
  
  ## Models
  ### Validation set; true outcomes
  VTmd <- multinom(fmly,data = vdata,Hess = TRUE,trace=FALSE)
  BV = coef(VTmd)
  BVV = vcov(VTmd) 
  Vdm = model.matrix(VTmd) 
  VTres = list("coef" = c(t(BV)),"std"=sqrt(diag(BVV))) # to be returned to compare
  
  ### Validation set; surrogate outcomes
  VSmd = glm(fmls, data = vdata,family = "binomial")
  GV = coef(VSmd)
  GVV = vcov(VSmd) # similar to GFV
  
  ### Full set; surrogate outcomes
  # fdata$swts = fs + (sum(1 - vs) / sum(1 - fs)) / (sum(vs) / sum(fs)) * (1 - fs)
  # w = (sum(vs) / sum(fs)) * fs + (sum(1 - vs) / sum(1 - fs)) * (1 - fs)
  w = fs + (sum(1 - vs) / sum(1 - fs)) / (sum(vs) / sum(fs)) * (1 - fs)
  FSmd = glm(fmls, data = fdata, family = "binomial", weights = w)
  GF = coef(FSmd)
  GFV = vcov(FSmd)
  Fdm = model.matrix(FSmd)
  
  ## Estimator
  # score function for beta (full)
  VTp = VTmd$fitted.values
  VTy = model.matrix(~ vdata[[ychar]] - 1)
  VTr = (VTy - VTp)[,-1]
  lv = sapply(1:n,function(i){c(VTr[i,]) %x% c(Vdm[i,])}) #  %>% t()
  
  # score function for gamma (full)
  gf = w * (fs - FSmd$fitted.values) * Fdm
  
  Hyinv = BVV * n # 6*6
  Hsinv = GFV * N # 3*3
  Hs = solve(Hsinv) # 3*3
  
  Gs = t(gf) %*% gf / N # 3*3
  Gsinv = solve(Gs) # 3*3
  Gsy = lv %*% gf[!is.na(fy), ]/ n # 6*3
  
  BA = c(t(BV)) - Hyinv %*% Gsy %*% Gsinv %*% Hs %*% (GV - GF)
  BAV = 1 / n * (Hyinv - (1 - n / N) * Hyinv %*% Gsy %*% Gsinv %*% t(Gsy) %*% Hyinv)
  BAres = list("coef" = c(t(BA)),"std"=sqrt(diag(BAV)))
  
  return(list('VT' = VTres, 'BA' = BAres))
}


# random sampling (method 1 & 3)
# method 1: Y~X on U
# method 3: augmented on U
fn_random <- function(fdata,xchar,ychar,schar){
  # fdata = tmpv
  # xchar = c('x1','x2')
  # ychar = 'y'
  # schar = 's'
  ## Settings
  fy = fdata[[ychar]]
  # TODO: to be checked (for the `multinom`)
  if(!is.factor(fy)){fdata[[ychar]] = factor(fy)}
  # fy = fdata[[ychar]]
  fs = fdata[[schar]]
  
  udata = subset(fdata, subset = !is.na(fy))
  # uy = udata[[ychar]]
  us = udata[[schar]]
  
  N = nrow(fdata)
  n = nrow(udata)
  
  fmly <- reformulate(xchar,response = ychar)
  fmls <- reformulate(xchar,response = schar)
  
  ## Models
  ### Validation set; true outcomes
  UTmd <- multinom(fmly,data = udata,Hess = TRUE,trace=FALSE)
  BU = coef(UTmd)
  BUV = vcov(UTmd) 
  Udm = model.matrix(UTmd) 
  UTres = list("coef" = c(t(BU)),"std"=sqrt(diag(BUV))) # to be returned to compare
  
  ### Validation set; surrogate outcomes
  USmd = glm(fmls, data = udata,family = "binomial")
  GU = coef(USmd)
  GUV = vcov(USmd) # similar to GFV
  
  ### Full set; surrogate outcomes
  FSmd = glm(fmls, data = fdata, family = "binomial")
  GF = coef(FSmd)
  GFV = vcov(FSmd)
  Fdm = model.matrix(FSmd)
  
  ## Estimator
  # score function for beta (full)
  UTp = UTmd$fitted.values
  UTy = model.matrix(~ udata[[ychar]] - 1)
  UTr = (UTy - UTp)[,-1]
  lu = sapply(1:n,function(i){c(UTr[i,]) %x% c(Udm[i,])}) #  %>% t()
  
  # score function for gamma (full)
  gu = (us - USmd$fitted.values) * Udm
  # gf = w * (fs - FSmd$fitted.values) * Fdm
  
  ## Matrix
  Uinv = BUV * n # 6*6
  C12 = lu %*% gu/ n # 6*3
  Vu = t(gu) %*% gu / n # 3*3
  Uu = solve(GUV * n) # 3*3
  
  cu = n/N
  
  UA = c(t(BU)) - Uinv %*% C12 %*% solve(Vu) %*% Uu %*% (GU - GF)
  UAV =(Uinv - (1 - cu) * Uinv %*% C12 %*% solve(Vu) %*% t(C12) %*% Uinv) / n
  UAres = list("coef" = c(t(UA)),"std"=sqrt(diag(UAV)))
  return(list('UT' = UTres, 'UA' = UAres))
}


# --- Example ------------

# true beta
BT = c(-2.75,1.00,1.00,-0.70,1.70,-0.20) # BT=beta true; p(y=1)=0.07

# data generation
df = fn_dataGenF(beta = BT,seed=6) 
dv = fn_dataGenV(df,n0=300,n1=300)
du = fn_dataGenU(df,n=600)

# estimators 
Roral = fn_oracle(df,c('x1','x2'),'y')
Rrand = fn_random(du,c('x1','x2'),'y','s') 
Rbias = fn_bias(dv,c('x1','x2'),'y','s')   

# results
Roral
Rrand # UT=method 1; UA=method 3
Rbias # VT=method 2; BA=TriCA

